<?xml version="1.0" encoding="utf-8"?>
<!-- Created by Leo: http://leoeditor.com/leo_toc.html -->
<leo_file xmlns:leo="http://leoeditor.com/namespaces/leo-python-editor/1.1" >
<leo_header file_format="2"/>
<globals/>
<preferences/>
<find_panel_settings/>
<vnodes>
<v t="leo.20220430145908.2"><vh>@data import-xml-tags</vh></v>
</vnodes>
<tnodes>
<t tx="leo.20220430145908.2">CoppeliaSim
environment
dynamics
simulation
camera
dummy
shape
mesh</t>
</tnodes>
</leo_file>
